blog/config/routes.rb
Rails.application.routes.draw do
  root "publishes#index"
  resources :publishes

end

blog/app/models/publish.rb
class Publish < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
  validates :content, presence: true

  validates :content, length: {
    maximum: 30,
    minimum: 3
  }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  def index
    @publishes = Publish.all()
  end

  def  edit
    @publish = Publish.find(params[:id])
  end

  def new
    @publish = Publish.new
  end

  def create
    @publish = Publish.create(publishes_params)
    if @publish.save
      redirect_to publish_path(@publish)
    else
      render :new
    end
  end

  def show
    @publish = Publish.find(params[:id])
  end

  def update
    @publish = Publish.find(params[:id])
    @publish.update(publishes_params)
    redirect_to publish_path(@publish)
  end

  def destroy
    @publish = Publish.find(params[:id])
    @publish.destroy
    redirect_to publishes_path
  end

  private
    def publishes_params
      params.require(:publish).permit(:title, :author, :content)
    end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/publishes_helper.rb
module PublishesHelper
end

blog/app/views/layouts/_header.html.erb
<h1>Holy Crap I'm A Header</h1>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/publishes/edit.html.erb
<%= render "layouts/header"%>
<%= form_for @publish, url: {action: 'update'} do |f|%>
  <%= f.label :title%>
  <%= f.text_field :title, value: @publish.title %>
  <br>
  <br>
  <%= f.label :author%>
  <%= f.text_field :author, value: @publish.author%>
  <br>
  <br>
  <%= f.label :content%>
  <%= f.text_area :content, value: @publish.content%>
  <br>
  <br>
  <%=f.submit%>
<% end %>

blog/app/views/publishes/index.html.erb
<%= render "layouts/header"%>
<h1>BLOGOSPHERE</h1>
<% @publishes.each do |publish| %>
  <h2><%= link_to publish.title, publish_path(publish)%></h2>
  <br>
  <h3><%= publish.author%></h3>
  <br>
  <p><%= publish.content%></p>
<% end %>
<br>
<%= link_to "Create a Post", new_publish_path%>

blog/app/views/publishes/new.html.erb
<%= render "layouts/header"%>
<% if @publish.errors %>

  <%= form_for @publish, url:{action: 'create'} do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%> <%=@publish.errors.full_messages[0]%>
    <br>
    <br>
    <%= f.label :author%>
    <%= f.text_field :author%><%=@publish.errors.full_messages[1]%>
    <br>
    <br>
    <%= f.label :content%>
    <%= f.text_area :content%><%=@publish.errors.full_messages[2]%>
    <br>
    <br>
    <%=f.submit%>
  <% end %>

<% else %>
  <%= form_for @publish, url:{action: 'create'} do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%>
    <br>
    <br>
    <%= f.label :author%>
    <%= f.text_field :author%>
    <br>
    <br>
    <%= f.label :content%>
    <%= f.text_area :content%>
    <br>
    <br>
    <%=f.submit%>
  <% end %>
<% end %>

blog/app/views/publishes/show.html.erb
<%= render "layouts/header"%>
  <h2><%= @publish.title %></h2>
  <br>
  <h3><%= @publish.author%></h3>
  <br>
  <p><%= @publish.content%></p>
  <br>
  <%= link_to "edit", edit_publish_path(@publish)%> |
  <%= link_to "delete", publish_path(@publish), method: :delete%> |
  <%= link_to "back home", publishes_path%>

blog/app/views/publishes/update.html.erb
<%= render "layouts/header"%>
<%=form_for @publish, url:{action: 'create'} do |f|%>
  <%= f.label :title%>
  <%= f.text_field :title%>
  <br>
  <%= f.label :author%>
  <%= f.text_field :author%>
  <br>
  <%= f.label :content%>
  <%= f.text_area :content%>
  <br>
  <%=f.submit%>
<% end %>