library/config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books, {only: [:show, :update, :index]}

end

library/app/models/book.rb
class Book < ActiveRecord::Base
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all()
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
    
  end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/helpers/books_helper.rb
module BooksHelper
end

library/app/views/books/index.html.erb
<h2>Books We Carry:</h2>
  <ul>
    <% @books.each do |book| %>
      <li><%= link_to book.title, book_path(book)%></li>
      <%=book.author%>
      <br>
      <br>
    <% end %>
  </ul>

library/app/views/books/show.html.erb
<% if @book.status == false %>
  <%= form_for @book, url: {action: 'update'} do |f|%>
    <%= f.label :title%>
    <%= f.label :author%>
    <%= f.checkbox :value @book.status %>
  <% end %>
<% end %>

library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Libre Los Libres</h1>
<%= yield %>

</body>
</html>